services:
  postgres:
    image: postgres:15
    container_name: college_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: collegedb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: college_redis
    restart: always
    ports:
      - '6380:6379'
  # nest:
  #   build: .
  #   container_name: college_nest
  #   restart: always
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: 1234567
  #     DATABASE_NAME: collegedb
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   depends_on:
  #     - postgres
  #     - redis

volumes:
  postgres_data:
